### ISSUE TITLE
npm errors

### ISSUE THREAD

**Issue by dgillier** [mikadoplus/videojs-google-chromecast#2]
Hello,

I'm trying to install you plugin by got the following errors:
Any idea what to do ?
Thanks, Denis

> vagrant@homestead:~/Code/BMS-0$ npm install --save mikadoplus/videojs-google-chromecast
> npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
> npm ERR! prepareGitDep npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
> npm ERR! prepareGitDep npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm ERR! prepareGitDep 
> npm ERR! prepareGitDep npm ERR! code EBADPLATFORM
> npm ERR! prepareGitDep npm ERR! notsup Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm ERR! prepareGitDep npm ERR! notsup Valid OS:    darwin
> npm ERR! prepareGitDep npm ERR! notsup Valid Arch:  any
> npm ERR! prepareGitDep npm ERR! notsup Actual OS:   linux
> npm ERR! prepareGitDep npm ERR! notsup Actual Arch: x64
> npm ERR! prepareGitDep 
> npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
> npm ERR! prepareGitDep npm ERR!     /home/vagrant/.npm/_logs/2020-06-08T16_56_48_125Z-debug.log
> npm ERR! prepareGitDep 
> npm ERR! premature close
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/vagrant/.npm/_logs/2020-06-08T16_56_48_212Z-debug.log

**Comment by mikadoplus** [comment]
@dgillier I don't think this is related to this plugin but rather to something on your configuration. If it is not a production platform I'll suggest to update your node and npm with these steps :

1. Remove the local directory node_modules and the package-lock.json
2. Clean the npm cache with: `npm cache verify`
3. Update the global npm with: `sudo npm i -g npm`
4. Reinstall the local with: `npm i` or `npm install`
5. Install the plugin: `npm install --save mikadoplus/videojs-google-chrome`

Even though there is more likely a problem with the fsevents plugin. This one isn't compatible with linux but with macOS (darwin).

If the error persists try to post here your npm and node versions.

Thanks

If there is no error you can continue installing this plugin :
6.

**Comment by dgillier** [comment]
@mikadoplus Hi, thanks for your answer.
Did what you suggested, but having same problem again...

npm -version
6.14.5
node -v
v12.16.1

**Comment by alexhackney** [comment]
@dgillier Are you using cross-env ? Looks like it's an env problem.

**Comment by mikadoplus** [comment]
I'v update the plugin to remove the dependency on fsevents package. The plugin still needs it through an other package so can easily stay as a dev-dependency, even though there is also the cross-env package with some parameters on webpack which I hope could bypass your install via npm.

Even though I do not advice to do it it like that you can give it a shot trying to install it as a dev dependency and see what your node will say : `npm install --save-dev mikadoplus/videojs-google-chromecast`

**Comment by dgillier** [comment]
Thanks for all your help !

regarding cross-dev, yes as I’m using Homestead running into a vagrant VM on OSX…

> npm install --save-dev mikadoplus/videojs-google-chromecast

Worked ;)

Thanks. Denis

**Comment by mikadoplus** [comment]
@dgillier hey thats nice to read. So closing this issue as it seems to work. Enjoy your casting ;).
